server:
  port: 8080

spring:
  application:
    name: inventory-service

# 로그 레벨 설정 (선택)
logging:
  level:
    root: INFO

# 테스트용 응답 메시지
inventory:
  message: Inventory service is running!
  data: inventory-response

# Swagger-UI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
